name: ping_me
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: "^0.9.3"
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
     - assets/images/login/
     - assets/images/logo/
  uses-material-design: true

flutter_icons:
  ios: true
  image_path: "assets/images/logo/app_icon.png"
